version: "3.0"
services:
  wals-server:
    image: bayes-cluster/wals-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    user: 'root'
    ports:
      - '3838:3838'
    volumes:
      - './shiny_logs:/var/log/shiny-server'